### ISSUE TITLE
Parse files with byte-order-mark

### ISSUE THREAD

**Issue by am11** [step-/JSON.awk#16]
When parsing a JSON file with BOM such as:

https://github.com/dotnet/toolset/blob/40cc5860e2ef311b9aca733b1d2eccaa681bd422/TestAssets/InstallationScriptTests/InstallationScriptTests.json

JSON.awk gives the following error:

```sh
/datadrive/projects/toolset/TestAssets/InstallationScriptTests/InstallationScriptTests.json: expected <value> but got <﻿> at input token 1
<<﻿>> { "sdk" : { "version" : "1.0.0-beta.19463.3" } }
```

Current workaround is to strip these charecters using tool like sed `sed '1s/^\xEF\xBB\xBF//' "$json_file" | awk -f JSON.awk - | ....`.

It would be nice if parser ignores these BOM characters so consumer do not need to strip them.

**Comment by step-** [comment]
Thank you
bd94b33
