### ISSUE TITLE
Example: parse sha of HEAD commit

### ISSUE THREAD

**Issue by nikkej** [step-/JSON.awk#22]
E.g. how to parse and print a single key  /  value pair ( or just a value for known key )

**Comment by step-** [comment]
Sure, I can show you more examples but I need some information to be able to focus on your needs:

* What have your tried? (actual code helps)
* How do you plan to use JSON.awk? (which OS, which language, describe your application, etc.)

**Comment by nikkej** [comment]
Oh, and os is Fedora Linux 35, x86_64 and ultimate goal is to have a hash of latest git commit in environment which is very bare (rpm src spec run on mock bootstrap where curl and awk (gawk) is installed as a default

**Comment by step-** [comment]
```sh
curl -s https://api.github.com/repos/step-/JSON.awk/commits/HEAD |
    awk -f /path/to/JSON.awk - |
    grep -F '["sha"]' |     # because you need key "sha"
    cut -d '"' -f4          # parse the sha

45ff4d0d7cf25f34324063cf983955d72b1151da
```

Of course, you need to know the full JSON path to the key whose value you are interested in. `JSON.awk` outputs a list of path-value lines. In this example it output:

```
... stuff before ...
["sha"] "45ff4d0d7cf25f34324063cf983955d72b1151da"
... stuff after...
```

Then `grep` grabbed that particular key-value line, and `cut` extracted the value.

The main advantages of callbacks are that you have the full power of awk string/regex manipulation at your disposal - as opposed to what the shell can do - and that your callbacks run in `JSON.awk`'s main loop, which leads to potentially fewer processes being forked.

The latter only matters if you need to extract lots of values, or modify them in non-trivial ways. If all you are doing is extracting one key-value pair like in the example I think `grep + cut` is just fine.

If you feel like it, you could combine `grep` and `cut` into a single command, for instance using an awk script.  Even better, @mohd-akram has complemented `JSON.awk` with a nice json for awk tool [jawk](https://github.com/mohd-akram/jawk), which puts everything we discussed together as an awk scriptlet.  With `jawk` the example above becomes:

```sh
curl -s https://api.github.com/repos/step-/JSON.awk/commits/HEAD |
    jawk '{ print _["sha"] }'

45ff4d0d7cf25f34324063cf983955d72b1151da
```

**Comment by nikkej** [comment]
This is great! Thank you so much, step-! I'll `can have grep + cut` for this particular case but definitely I'm willing to learn use callbacks and awk programming among that
