### ISSUE TITLE
mawk 1.3.3 support (Debian/Ubuntu)

### ISSUE THREAD

**Issue by urban-1** [step-/JSON.awk#6]
It seems that the script is not mawk compatible. Running with test file:

```
{
    "asd":1
}
```

Result:

```
./test.json: expected <string> but got <EOF> at input token 2
{ <<EOF>>          " a s d "
invalid: ./test.json
expected <string> but got <EOF> at input token 2
{ <<EOF>>          " a s d "
```

System info:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
```

AWK: `ii  mawk                                      1.3.3-17ubuntu2 `

It works as expected with `gawk`.

**Comment by step-** [comment]
Thanks for your report. I can't reproduce this issue, at the moment.
How did you start JSON.awk? Can you please post the output of `xxd test.json`? Can you try with mawk 1.3.4? 
```sh
# mawk -W version
mawk 1.3.4 20150503
Copyright 2008-2014,2015, Thomas E. Dickey
Copyright 1991-1996,2014, Michael D. Brennan

random-funcs:       srandom/random
regex-funcs:        internal
compiled limits:
sprintf buffer      8192
maximum-integer     2147483647
# cat reproduce-issue-6.json 
{
    "asd":1
}
# xxd reproduce-issue-6.json 
00000000: 7b0a 2020 2020 2261 7364 223a 310a 7d0a  {.    "asd":1.}.
# printf "%s\n" reproduce-issue-6.json "" | mawk -f JSON.awk
["asd"]	1
# 
```

**Comment by step-** [comment]
Packages for Ubuntu here: ftp://invisible-island.net/DEBS/amd64/
linked from http://invisible-island.net/mawk/

**Comment by urban-1** [comment]
You are right! I downloaded `mawk 1.3.4 20161120` and everything worked!

It seems that Debian and Ubuntu are stuck with mawk 1.3.3:
- https://bugs.launchpad.net/ubuntu/+source/mawk/+bug/1332114
- https://packages.debian.org/search?keywords=mawk)

... which is now 21 years old!!! :)

I don't think that it worth fixing... but you can leave it here for visibility - whatever you prefer

**Comment by step-** [comment]
Thank you for reporting your success. I will start a FAQ and link this page.

**Comment by step-** [comment]
I found another case where mawk mawk 1.3.4 20150503 doesn't work. It works with gawk. Can you please run the same  test with 1.3.4 20161120 and report results here? Thanks.
```sh
# { echo; curl -s https://raw.githubusercontent.com/archan937/jsonv.sh/master/examples/complex-1.json; } | mawk -f JSON.awk 
-: expected <value> but got <:> at input token 1
<<:>> "male" , "company" : "Myopium" , "email" : "gregorydalton@myopium.com" , 
invalid: -
expected <value> but got <:> at input token 1
<<:>> "male" , "company" : "Myopium" , "email" : "gregorydalton@myopium.com" , 
# 
```

**Comment by urban-1** [comment]
I do get the same:

```
/tmp/mawk-1.3.4-20161120$ { echo; curl -s https://raw.githubusercontent.com/archan937/jsonv.sh/master/examples/complex-1.json; } | ./mawk -f JSON.awk
mawk: cannot open JSON.awk (No such file or directory)
urban@urban-kde:/tmp/mawk-1.3.4-20161120$ nano ./JSON.awk
urban@urban-kde:/tmp/mawk-1.3.4-20161120$ { echo; curl -s https://raw.githubusercontent.com/archan937/jsonv.sh/master/examples/complex-1.json; } | ./mawk -f JSON.awk
-: expected <value> but got <:> at input token 1
<<:>> "male" , "company" : "Myopium" , "email" : "gregorydalton@myopium.com" ,
invalid: -
expected <value> but got <:> at input token 1
<<:>> "male" , "company" : "Myopium" , "email" : "gregorydalton@myopium.com" ,
```

Is it the space before `:`?

**Comment by step-** [comment]
It seems to be a buffering mode issue that can affect all awk variants, including gawk, when JSON.awk reads json data from stdin. Recall that stdin is used to feed the list of input files to JSON.awk:
```
echo -e "1.json\n2.json\n" | awk -f JSON.awk
```
To last '\n' produces an empty line, which tells JSON.awk that the filename list is finished. To pipe data into JSON.awk we tell it that the input file is "-", then write json data to JSON.awk's stdin.
```
{ echo -e "-\n" ; curl -s $URL; } | awk -f JSON.awk
{ echo; curl -s $URL; } | awk -f JSON.awk
```
(the two forms are equivalent)

Note that JSON.awk's stdin carries both the filename list and the json data. This can work without confusion only if I/O is line-buffered, so JSON.awk breaks reads at each newline. It reads "-\n" and breaks, then echo's implicit "\n" and breaks, it understands that's the end of the filename list so it starts reading json-data at offset 0 after "\n". That's exactly where the json data begins in stdin, and everything works well.
But if I/O isn't line-buffered, then JSON.awk is likely to read past "\n\n", say 256 characters, so the json data reading cycle begins at a positive offset after "\n", which means that some characters at the beginning of the json data will be consumed without being parsed. That's what happens, I think.
It did some tests and managed to mitigate this issue by using `stdbuf -oL` in the left side command of the shell pipe, but the effectiveness depends on the kinds of commands that are involved, and varies with gawk vs. mawk. I don't think it's a good solution.
Probably a better solution is to change usage syntax, in which filename arguments are given on stdin, and instead specify filename arguments on the command-line. That should eliminate line-buffering concerns altogether.
I need to think over why I designed this quirky stdin filename list mechanism originally. Probably it was a design requirement of the project that used JSON.awk at the time, but now it's just an issue.

**Comment by step-** [comment]
I think I will change it this way:
 * By default file name arguments are passed on stdin, as it is already. Reason: be backward compatible.
 * If `-v CMDLINE=1` is given then get file name arguments from the command line instead of stdin.

**Comment by urban-1** [comment]
Hi @step- 

I think your solution will work. You can also make the decision based on [`ARGC`](https://www.gnu.org/software/gawk/manual/html_node/ARGC-and-ARGV.html) but I don't know if that is compatible with all `awk` versions.

**Comment by step-** [comment]
Command-line arguments migrated to issue #8.
