### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by aafin** [step-/JSON.awk#9]
>gawk: JSON.awk:231: (FILENAME=c.tmp FNR=1) fatal: delete: illegal use of variable `JPATHS' as array

My gawk can not delete befor use.

split("",JPATHS)   
is better than 
delete JPATHS;

**Comment by step-** [comment]
Hi aafin,

can you please attach file c.tmp and show me the command-line that results in this error so I can try to reproduce it here? Thanks.
Also, what gawk version is yours? What operating system and OS version? Thanks.

**Comment by aafin** [comment]
GNU Awk 3.1.0 for Windows. (It's funny, I know)

gawk -f JSON.awk AnyFile

When I replaced delete JPATHS; with split("",JPATHS) everything turned OK

**Comment by step-** [comment]
Gnu awk 3.1.0 for Windows released 2001-06-17.
